name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
            cd /home/${{ secrets.SSH_USER }}/autoOM || exit
            git fetch origin
            git reset --hard origin/main
            git pull
            sudo chmod +x /home/${{ secrets.SSH_USER }}/autoOM/main.sh
            /home/${{ secrets.SSH_USER }}/autoOM/main.sh
     
